# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tsHistogram <- function(x, tlag, npartitions) {
    .Call('nonlinearTseries_tsHistogram', PACKAGE = 'nonlinearTseries', x, tlag, npartitions)
}

mutualInformation <- function(tseries, maxlag, npartitions) {
    .Call('nonlinearTseries_mutualInformation', PACKAGE = 'nonlinearTseries', tseries, maxlag, npartitions)
}

