// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tsHistogram
NumericMatrix tsHistogram(NumericVector& x, int& tlag, const int& npartitions);
RcppExport SEXP nonlinearTseries_tsHistogram(SEXP xSEXP, SEXP tlagSEXP, SEXP npartitionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int& >::type tlag(tlagSEXP);
    Rcpp::traits::input_parameter< const int& >::type npartitions(npartitionsSEXP);
    __result = Rcpp::wrap(tsHistogram(x, tlag, npartitions));
    return __result;
END_RCPP
}
// mutualInformation
NumericVector mutualInformation(const NumericVector& tseries, const int& maxlag, const int& npartitions);
RcppExport SEXP nonlinearTseries_mutualInformation(SEXP tseriesSEXP, SEXP maxlagSEXP, SEXP npartitionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericVector& >::type tseries(tseriesSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxlag(maxlagSEXP);
    Rcpp::traits::input_parameter< const int& >::type npartitions(npartitionsSEXP);
    __result = Rcpp::wrap(mutualInformation(tseries, maxlag, npartitions));
    return __result;
END_RCPP
}
