# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generalized_correlation_sum <- function(timeSeries, timeLag, theilerWindow, radii, minEmbeddingDim, maxEmbeddingDim, corrSumOrder, numberBoxes) {
    .Call('_nonlinearTseries_generalized_correlation_sum', PACKAGE = 'nonlinearTseries', timeSeries, timeLag, theilerWindow, radii, minEmbeddingDim, maxEmbeddingDim, corrSumOrder, numberBoxes)
}

calculate_fluctuation_function <- function(yr, windowSizesVector) {
    .Call('_nonlinearTseries_calculate_fluctuation_function', PACKAGE = 'nonlinearTseries', yr, windowSizesVector)
}

rcpp_information_dimension <- function(timeSeries, embeddingDimensions, timeLag, fixedMasses, radius, increasingRadiusFactor, nBoxes, nReferenceVectors, theilerWindow, nNeighbours) {
    .Call('_nonlinearTseries_rcpp_information_dimension', PACKAGE = 'nonlinearTseries', timeSeries, embeddingDimensions, timeLag, fixedMasses, radius, increasingRadiusFactor, nBoxes, nReferenceVectors, theilerWindow, nNeighbours)
}

lyapunov_exponent <- function(timeSeries, minEmbeddingDim, maxEmbeddingDim, timeLag, radius, theilerWindow, minNumNeighbours, nRefPoints, maxTimeSteps, nBoxes) {
    .Call('_nonlinearTseries_lyapunov_exponent', PACKAGE = 'nonlinearTseries', timeSeries, minEmbeddingDim, maxEmbeddingDim, timeLag, radius, theilerWindow, minNumNeighbours, nRefPoints, maxTimeSteps, nBoxes)
}

calculate_time_series_histogram <- function(x, timeLag, nPartitions) {
    .Call('_nonlinearTseries_calculate_time_series_histogram', PACKAGE = 'nonlinearTseries', x, timeLag, nPartitions)
}

calculate_mutual_information <- function(tseries, maxlag, nPartitions) {
    .Call('_nonlinearTseries_calculate_mutual_information', PACKAGE = 'nonlinearTseries', tseries, maxlag, nPartitions)
}

getVectorNeighbours <- function(phaseSpace, vectorIndex, radius, numberBoxes) {
    .Call('_nonlinearTseries_getVectorNeighbours', PACKAGE = 'nonlinearTseries', phaseSpace, vectorIndex, radius, numberBoxes)
}

getAllNeighbours <- function(phaseSpace, radius, numberBoxes) {
    .Call('_nonlinearTseries_getAllNeighbours', PACKAGE = 'nonlinearTseries', phaseSpace, radius, numberBoxes)
}

get_NN_2Set_wrapper <- function(data, query, dimension, ND, NQ, K, EPS, SEARCHTYPE, USEBDTREE, SQRAD, nn_index, distances) {
    .Call('_nonlinearTseries_get_NN_2Set_wrapper', PACKAGE = 'nonlinearTseries', data, query, dimension, ND, NQ, K, EPS, SEARCHTYPE, USEBDTREE, SQRAD, nn_index, distances)
}

nonlinear_noise_reduction <- function(timeSeries, embeddingDimension, radius, nBoxes) {
    .Call('_nonlinearTseries_nonlinear_noise_reduction', PACKAGE = 'nonlinearTseries', timeSeries, embeddingDimension, radius, nBoxes)
}

poincare_map <- function(timeSeries, hiperplanePoint, normalVector) {
    .Call('_nonlinearTseries_poincare_map', PACKAGE = 'nonlinearTseries', timeSeries, hiperplanePoint, normalVector)
}

get_rqa_histograms <- function(neighs, nneighs, ntakens, vmin, lmin) {
    .Call('_nonlinearTseries_get_rqa_histograms', PACKAGE = 'nonlinearTseries', neighs, nneighs, ntakens, vmin, lmin)
}

space_time_plot <- function(phaseSpace, radii, nTimeSteps, timeStep, nPercentages) {
    .Call('_nonlinearTseries_space_time_plot', PACKAGE = 'nonlinearTseries', phaseSpace, radii, nTimeSteps, timeStep, nPercentages)
}

neighsList2Sparse <- function(neighs, neighs_matrix) {
    invisible(.Call('_nonlinearTseries_neighsList2Sparse', PACKAGE = 'nonlinearTseries', neighs, neighs_matrix))
}

neighsList2SparseRCreator <- function(neighs, ntakens, neighs_matrix) {
    invisible(.Call('_nonlinearTseries_neighsList2SparseRCreator', PACKAGE = 'nonlinearTseries', neighs, ntakens, neighs_matrix))
}

