# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generalized_correlation_sum <- function(timeSeries, timeLag, theilerDistance, radii, minEmbeddingDim, maxEmbeddingDim, corrSumOrder, numberBoxes) {
    .Call('nonlinearTseries_generalized_correlation_sum', PACKAGE = 'nonlinearTseries', timeSeries, timeLag, theilerDistance, radii, minEmbeddingDim, maxEmbeddingDim, corrSumOrder, numberBoxes)
}

calculateFluctuationFunction <- function(yr, windowSizesVector) {
    .Call('nonlinearTseries_calculateFluctuationFunction', PACKAGE = 'nonlinearTseries', yr, windowSizesVector)
}

timesTwo <- function(x) {
    .Call('nonlinearTseries_timesTwo', PACKAGE = 'nonlinearTseries', x)
}

tsHistogram <- function(x, tlag, npartitions) {
    .Call('nonlinearTseries_tsHistogram', PACKAGE = 'nonlinearTseries', x, tlag, npartitions)
}

mutualInformation <- function(tseries, maxlag, npartitions) {
    .Call('nonlinearTseries_mutualInformation', PACKAGE = 'nonlinearTseries', tseries, maxlag, npartitions)
}

getVectorNeighbours <- function(phaseSpace, vectorIndex, radius, numberBoxes) {
    .Call('nonlinearTseries_getVectorNeighbours', PACKAGE = 'nonlinearTseries', phaseSpace, vectorIndex, radius, numberBoxes)
}

getAllNeighbours <- function(phaseSpace, radius, numberBoxes) {
    .Call('nonlinearTseries_getAllNeighbours', PACKAGE = 'nonlinearTseries', phaseSpace, radius, numberBoxes)
}

test <- function(x) {
    .Call('nonlinearTseries_test', PACKAGE = 'nonlinearTseries', x)
}

neighsList2Sparse <- function(neighs, neighs_matrix) {
    invisible(.Call('nonlinearTseries_neighsList2Sparse', PACKAGE = 'nonlinearTseries', neighs, neighs_matrix))
}

neighsList2SparseRCreator <- function(neighs, ntakens, neighs_matrix) {
    invisible(.Call('nonlinearTseries_neighsList2SparseRCreator', PACKAGE = 'nonlinearTseries', neighs, ntakens, neighs_matrix))
}

