# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generalized_correlation_sum <- function(timeSeries, timeLag, theilerWindow, radii, minEmbeddingDim, maxEmbeddingDim, corrSumOrder, numberBoxes) {
    .Call('nonlinearTseries_generalized_correlation_sum', PACKAGE = 'nonlinearTseries', timeSeries, timeLag, theilerWindow, radii, minEmbeddingDim, maxEmbeddingDim, corrSumOrder, numberBoxes)
}

calculateFluctuationFunction <- function(yr, windowSizesVector) {
    .Call('nonlinearTseries_calculateFluctuationFunction', PACKAGE = 'nonlinearTseries', yr, windowSizesVector)
}

rcpp_information_dimension <- function(timeSeries, embeddingDimensions, timeLag, fixedMasses, radius, increasingRadiusFactor, nBoxes, nReferenceVectors, theilerWindow, nNeighbours) {
    .Call('nonlinearTseries_rcpp_information_dimension', PACKAGE = 'nonlinearTseries', timeSeries, embeddingDimensions, timeLag, fixedMasses, radius, increasingRadiusFactor, nBoxes, nReferenceVectors, theilerWindow, nNeighbours)
}

lyapunov_exponent <- function(timeSeries, minEmbeddingDim, maxEmbeddingDim, timeLag, radius, theilerWindow, minNumNeighbours, nRefPoints, maxTimeSteps, nBoxes) {
    .Call('nonlinearTseries_lyapunov_exponent', PACKAGE = 'nonlinearTseries', timeSeries, minEmbeddingDim, maxEmbeddingDim, timeLag, radius, theilerWindow, minNumNeighbours, nRefPoints, maxTimeSteps, nBoxes)
}

tsHistogram <- function(x, tlag, npartitions) {
    .Call('nonlinearTseries_tsHistogram', PACKAGE = 'nonlinearTseries', x, tlag, npartitions)
}

mutualInformation <- function(tseries, maxlag, npartitions) {
    .Call('nonlinearTseries_mutualInformation', PACKAGE = 'nonlinearTseries', tseries, maxlag, npartitions)
}

getVectorNeighbours <- function(phaseSpace, vectorIndex, radius, numberBoxes) {
    .Call('nonlinearTseries_getVectorNeighbours', PACKAGE = 'nonlinearTseries', phaseSpace, vectorIndex, radius, numberBoxes)
}

getAllNeighbours <- function(phaseSpace, radius, numberBoxes) {
    .Call('nonlinearTseries_getAllNeighbours', PACKAGE = 'nonlinearTseries', phaseSpace, radius, numberBoxes)
}

test <- function(x, y) {
    .Call('nonlinearTseries_test', PACKAGE = 'nonlinearTseries', x, y)
}

neighsList2Sparse <- function(neighs, neighs_matrix) {
    invisible(.Call('nonlinearTseries_neighsList2Sparse', PACKAGE = 'nonlinearTseries', neighs, neighs_matrix))
}

neighsList2SparseRCreator <- function(neighs, ntakens, neighs_matrix) {
    invisible(.Call('nonlinearTseries_neighsList2SparseRCreator', PACKAGE = 'nonlinearTseries', neighs, ntakens, neighs_matrix))
}

